---
deployment:
  tasks:
    - export DEPLOYPATH=/home/industryarch/public_html
    - /bin/rm -rf $DEPLOYPATH/assets
    - /usr/bin/rsync -a dist/ $DEPLOYPATH/
    - /usr/bin/rsync -a --exclude=config.php --exclude=test-smtp.php api/ $DEPLOYPATH/api/
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    - /bin/mkdir -p $DEPLOYPATH/uploads
    - /bin/cp uploads/.htaccess $DEPLOYPATH/uploads/.htaccess
    - /bin/rm -f $DEPLOYPATH/api/contact/test-smtp.php
